version: '3'

services:
  aliasmate-test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - ALIASMATE_TEST_MODE=true
    command: |
      bash -c "
        echo 'Installing AliasMate from local source...'
        cd /app && ./scripts/install.sh
        echo 'Installation complete! Starting shell...'
        exec bash
      "
