name: Build and Test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck jq dialog
      
      - name: Run shellcheck
        run: |
          find ./src -type f -name "*.sh" -exec shellcheck -x {} \;
      
      - name: Run unit tests
        run: |
          chmod +x ./scripts/run_tests.sh
          ./scripts/run_tests.sh
  
  build:
    name: Build packages
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck jq ruby ruby-dev rubygems build-essential rpm
          sudo gem install --no-document fpm
      
      - name: Build packages
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: dist/
          retention-days: 7
